### ISSUE TITLE
camelCase vs snake_case

### ISSUE THREAD

**Issue by jblachly** [blachlylab/dhtslib#20]
We have a split personality, sometimes using D-idiomatic camelCase and other times using python style snake_case.  We need to unify this, and better to do it before 1.0 because would be an API breaking change.

**Comment by charlesgregory** [comment]
Part of this is due to htslib's choice of snake_case. I should think we should match closely to htslib for those that may be used to the C API. IMO snake_case is much better than camelCase, however, we are writing D and should conform to their guidelines. I'm sure someone would bring it up if the package became popular.

**Comment by jblachly** [comment]
Actually doing way better than I thought and I think we only needed to fixup one file (in `dhtslib.` namespace).

Obviously, will leave the `htslib.` API the same
