### ISSUE TITLE
SAM Tags

### ISSUE THREAD

**Issue by jblachly** [blachlylab/dhtslib#32]
Make sure `dhtslib.tags` is conformant with Section 1.5
(https://samtools.github.io/hts-specs/SAMv1.pdf)

The module docstring does not seem to match the code (latter of which includes 'A', so it may be up to date but hard to tell)

Also, see [https://github.com/samtools/hts-specs/blob/master/SAMtags.pdf](https://github.com/samtools/hts-specs/blob/master/SAMtags.pdf) in case we want to define string descriptions for actual tags (that's a wishlist / good first issue item)

**Comment by jblachly** [comment]
@charlesgregory I believe the code in `dhtslib.tagvalue` is wrong, at least based on the module docstring.

Here, you have characters c,C,s,S,I  in the TypeChars, but these are only format specifier prefix characters for the Type `B`:

"For  an  integer  or  numeric  array  (type  ‘B’),  the  first  letter  indicates  the  type  of  numbers  in  the  followingcomma separated array.  The letter can be one of ‘cCsSiIf’, corresponding toint8t(signed 8-bit integer),uint8t(unsigned 8-bit integer),int16t,uint16t,int32t,uint32tandfloat, respectively."

Your unittests do include type e.g. `Bs`, but you also have primary types like `I2`. Of course I cannot see your test bam, did you generate it by hand?

**Comment by charlesgregory** [comment]
So I think the issue here is that in SAM format doesn't define c,C,s,S,I for the basic types, and when you view a BAM file as SAM all c,C,s,S,i,I types are converted to just i. Since it is a text representation we generally don't care if the number is a ubyte or a short.
However since we read in BAM in dhtslib (bam_1t), all integers are stored in their smallest possible form. This gave me issues when writing the unittests using the test bam provided by htslib as I used sam view to look at the tags and confirm their values. Since I was viewing SAM all the number tags were of type i. Though in BAM they actually encompass all the types (c,C,s,S,i,I).

**Comment by charlesgregory** [comment]
From 4.2.4 Auxiliary data encoding in the SAM Spec:
>While all single (i.e., non-array) integer types are stored in SAM as ‘i’, in BAM any of ‘cCsSiI’ may
be used together with the correspondingly-sized binary integer value, chosen according to the field value’s
magnitude.31 Similarly floating point ‘f’ fields are represented as IEEE 754-2008 binary32 values. Thus
BAM numeric fields have a total length of 4, 5, or 7 bytes:

**Comment by jblachly** [comment]
Documentation still needs tobe updated/improved, but I will close this issue
