### ISSUE TITLE
SAMRecord.qscores setter and getter have different Phred defaults

### ISSUE THREAD

**Issue by jblachly** [blachlylab/dhtslib#52]
This leads to a failing unit test , which I am disabling for now, but is also poor API design

@charlesgregory can you decide which should be the default, and make consistent? 

Also, I think even though D allows `char` type to have a value e.g. in the 1-40 range, doesn't mean we should encourage it, or even enable it (which `qscores!false` facilitates). If they want raw scores they can pass `ubyte` do'n t you think?

https://github.com/blachlylab/dhtslib/blob/9df93725233fcb1ce97832c733eed2f806196a19/source/dhtslib/sam/package.d#L345-L368

**Comment by jblachly** [comment]
Oh also the failing unit test:

https://github.com/blachlylab/dhtslib/blob/9df93725233fcb1ce97832c733eed2f806196a19/source/dhtslib/sam/package.d#L638

I couldn't figure it out

**Comment by charlesgregory** [comment]
Perhaps the best way to remedy all of this is to have the qscore getters and setters always deal in ```const(ubyte)[]``` of raw base quality scores with no templating. Then we simply have a function for phred scaling quality scores which takes a ```const(ubyte)[]``` and  returns ```const(char)[]```. Then there is no question of how everything works and ```read.qscores = whatever``` will actually work. It currently doesn't work because read.qscores is templated.
